spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver 
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/weiselldb?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non-null
    
server:
  servlet:
    context-path: /wei-sell 
  port: 8080