spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver 
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/weiselldb?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non-null
  redis:
    host: 127.0.0.1
    port: 6379
    
server:
  servlet:
    context-path: /wei-sell 
  port: 8080
  
wechat:
  #微信公众平台报备后获得的公众号的Id和密钥(用于手机微信的公众号授权登录)
  mpAppId: xxxxxxxxxx
  mpAppSecret: xxxxxxxxxx
  
  #以企业身份在微信开放平台报备后获得的Id和密钥（用于网页应用授权登录）
  openAppId: xxxxxxxxx
  openAppSecret: xxxxxxxxxx
  
  #微信公众平台模板消息的id，orderStatus是变量名，可自定义，这里表示是订单状态变更的模板
  templateId:
    orderStatus: xxxxxxx
  
  
projecturl:
  wechatMpAuthorize: http://walkerl.cn
  wechatOpenAuthorize: http://walkerl.cn
  wei-sell: http://walkerl.cn
  