spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver 
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/weiselldb?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non-null
  redis:
    host: 127.0.0.1
    port: 6379
    
server:
  servlet:
    context-path: /wei-sell 
  port: 8080
  
wechat:
  #微信公众平台报备后获得的公众号的Id和密钥(用于手机微信的公众号授权登录)
  mpAppId: wx3e4c666a1cf349c0
  mpAppSecret: 833c8ada8149e699c09247882f545f82
  
  #以企业身份在微信开放平台报备后获得的Id和密钥（用于网页应用授权登录）
  openAppId: xxxxxxxxx
  openAppSecret: xxxxxxxxxx
  
  
projecturl:
  wechatMpAuthorize: http://walkerl.cn
  wechatOpenAuthorize: http://walkerl.cn
  wei-sell: http://walkerl.cn
  